"""
Partner collected data: template, validation, training and scoring.

    python -m tools.partner_data template --out data/external/partner_example [--mode fault_labels]
    python -m tools.partner_data validate --root data/external/partner
    python -m tools.partner_data train    --root data/external/partner [--model models/partner.joblib]
    python -m tools.partner_data score    --root data/external/new_batch --model models/partner.joblib

template  writes a complete example dataset (dataset.json, recordings.csv and
          CSV files) with telemetry, accelerometer, motor current and power, so
          the expected format can be copied exactly. The signals are SYNTHETIC.
validate  checks files, columns, timestamps, missing values, labels and runs
train     extracts window features and trains the models that label_mode allows
score     applies saved models to a new dataset folder with the same channels
"""

import argparse
import csv
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import joblib  # noqa: E402
import numpy as np  # noqa: E402

import config  # noqa: E402
from datasets.partner_dataset import PartnerDatasetAdapter  # noqa: E402
from datasets.partner_schema import SchemaError  # noqa: E402
from predictive import partner_models  # noqa: E402

EXAMPLE_CHANNELS = [
    {"name": "position", "column": "position_rad", "type": "position", "unit": "rad"},
    {"name": "target", "column": "target_rad", "type": "target_position", "unit": "rad"},
    {"name": "velocity", "column": "velocity_rad_s", "type": "velocity", "unit": "rad/s"},
    {"name": "torque", "column": "torque_nm", "type": "torque", "unit": "N m"},
    {"name": "current", "column": "motor_current_a", "type": "current", "unit": "A"},
    {"name": "power", "column": "power_w", "type": "power", "unit": "W"},
    {"name": "accel", "column": "accel_g", "type": "vibration", "unit": "g"},
    {"name": "motor_temp", "column": "motor_temp_c", "type": "temperature", "unit": "C"},
    {"name": "ambient", "column": "ambient_c", "type": "ambient_temperature", "unit": "C"},
]


def _thermal(t, start_c, ambient_c, loss_w, resistance, tau, cooling=1.0):
    """First order warm-up: T -> ambient + loss * R * cooling with time constant tau."""
    steady = ambient_c + loss_w * resistance * cooling
    return steady + (start_c - steady) * np.exp(-t / tau)


def _synthetic(rng, seconds, rate, joint, fault, severity, life=None):
    """Plausible joint signals. SYNTHETIC: only for showing the file format and testing code."""
    t = np.arange(int(seconds * rate)) / rate
    phase = rng.uniform(0, 2 * np.pi)
    target = 0.8 * np.sin(2 * np.pi * 0.25 * t + phase) + 0.2 * joint
    velocity = np.gradient(target, t)
    lag = 0.004 + (0.03 * severity if fault in ("BACKLASH",) else 0.0)
    position = target - lag * velocity + rng.normal(0, 0.0005, t.shape)
    friction = 4.0 + (18.0 * severity if fault == "FRICTION" else 0.0)
    torque = 35 * np.cos(target) + friction * np.sign(velocity) + rng.normal(0, 0.6, t.shape)
    current = torque / 2.1 + rng.normal(0, 0.15, t.shape)
    power = torque * velocity
    mesh = 48.0 * (1.0 + 0.2 * joint)
    accel = 0.05 * np.sin(2 * np.pi * mesh * t) + rng.normal(0, 0.02, t.shape)
    if fault == "BEARING":
        impacts = (np.sin(2 * np.pi * 7.3 * t) > 0.99).astype(float)
        accel += severity * 0.6 * impacts * np.sin(2 * np.pi * 60 * t) + rng.normal(0, 0.02 * severity, t.shape)
    if life is not None:
        wear = np.exp(5 * (life - 1.0))
        accel += wear * 0.25 * rng.normal(0, 1, t.shape)
        torque += wear * 10 * np.sign(velocity)
        current = torque / 2.1 + rng.normal(0, 0.15, t.shape)
    ambient = 24.0 + 0.3 * np.sin(2 * np.pi * t / 3600.0) + rng.normal(0, 0.05, t.shape)
    loss = 0.004 * np.mean(torque ** 2) + 3.0
    cooling = 1.0 + (2.2 * severity if fault == "COOLING" else 0.0)
    if fault == "FRICTION":
        loss *= 1.0 + 0.8 * severity
    motor_temp = _thermal(t + start_offset[0], 24.5, 24.0, loss, 0.5, 25.0, cooling) \
        + rng.normal(0, 0.05, t.shape)
    return t, position, target, velocity, torque, current, power, accel, motor_temp, ambient


def command_template(args):
    out = args.out
    rng = np.random.RandomState(3)
    rate = 250.0        # keeps the example files small; real data can be faster
    os.makedirs(os.path.join(out, "raw"), exist_ok=True)
    schema = {
        "name": "partner_robot_joint_data_example",
        "system": "Describe the robot, joints and sensors here (model, gearbox, accelerometer position)",
        "description": "SYNTHETIC EXAMPLE generated by tools.partner_data template. Replace with real data.",
        "format": "csv",
        "sample_rate_hz": rate,
        "time_column": "time_s",
        "joint_column": "joint",
        "csv_delimiter": ",",
        # The example robot repeats a 4 s motion cycle. A window must cover a
        # whole cycle, otherwise healthy features change with position in the
        # cycle and look like anomalies.
        "window_seconds": 4.0,
        "hop_seconds": 1.0,
        # Temperature moves over minutes, so it uses a longer trailing window,
        # and the first minutes of a recording are warm-up, not steady state.
        "temperature_window_seconds": 20.0,
        "warmup_skip_seconds": 10.0,
        "label_mode": args.mode,
        "healthy_label": "HEALTHY",
        "channels": EXAMPLE_CHANNELS,
    }
    rows = []
    plan = []
    if args.mode == "fault_labels":
        for i in range(4):
            plan.append(("HEALTHY", None, 0.0, "load_5kg"))
        for fault in ("FRICTION", "BEARING", "BACKLASH", "COOLING"):
            for i in range(2):
                plan.append((fault, fault, 0.7, "load_5kg"))
    elif args.mode == "unlabeled":
        for i in range(5):
            plan.append(("", None, 0.0, "load_5kg"))
        plan.append(("", "BEARING", 0.8, "load_5kg"))
    else:
        for i in range(4):
            plan.append(("RUN_TO_FAILURE", None, 0.0, "load_5kg"))

    for index, (label, fault, severity, condition) in enumerate(plan):
        run_id = "run_%02d" % (index + 1)
        if args.mode == "run_to_failure":
            snapshots = 12
            for k in range(snapshots):
                life = k / float(snapshots - 1)
                start = k * 3600.0
                name = "raw/%s_snap%02d.csv" % (run_id, k)
                _write_csv(os.path.join(out, name), rng, 6.0, rate, fault, severity, life, start)
                rows.append({"file": name, "run_id": run_id, "asset_id": "robot_A", "condition": condition,
                             "label": label, "fault_joint": "", "start_time_s": "%.0f" % start,
                             "failure_time_s": "%.0f" % ((snapshots - 1) * 3600.0 + 6.0), "notes": ""})
        else:
            name = "raw/%s.csv" % run_id
            _write_csv(os.path.join(out, name), rng, 48.0, rate, fault, severity, None, 0.0)
            rows.append({"file": name, "run_id": run_id, "asset_id": "robot_A", "condition": condition,
                         "label": label, "fault_joint": "2" if fault else "",
                         "start_time_s": "", "failure_time_s": "",
                         "notes": "synthetic %s" % (fault or "normal")})

    with open(os.path.join(out, config.PARTNER_SCHEMA_FILE), "w") as handle:
        json.dump(schema, handle, indent=2)
    from datasets.partner_schema import RECORDING_COLUMNS
    with open(os.path.join(out, config.PARTNER_RECORDINGS_FILE), "w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=RECORDING_COLUMNS)
        writer.writeheader()
        writer.writerows(rows)
    print("Example dataset (%s, SYNTHETIC) written to %s: %d files" % (args.mode, out, len(rows)))


start_offset = [0.0]


def _write_csv(path, rng, seconds, rate, fault, severity, life, start):
    start_offset[0] = start
    with open(path, "w", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["time_s", "joint"] + [c["column"] for c in EXAMPLE_CHANNELS])
        for joint in (1, 2):
            signals = _synthetic(rng, seconds, rate, joint, fault if joint == 2 else None, severity, life)
            t = signals[0]
            for i in range(t.shape[0]):
                writer.writerow(["%.4f" % (start + t[i]), joint] + ["%.5g" % s[i] for s in signals[1:]])


def command_validate(args):
    adapter = _adapter(args.root)
    report = adapter.validate()
    d = report["dataset"]
    print("Dataset %s: %s, %d recordings, %d runs, label_mode %s" % (
        d["name"], d["format"], d["recordings"], report["runs"], d["label_mode"]))
    print("Channels: %s" % ", ".join("%s (%s, %s)" % (c["name"], c["type"], c["unit"]) for c in d["channels"]))
    print("Labels (runs per label): %s" % report["labels"])
    for error in report["errors"]:
        print("ERROR   %s" % error)
    for warning in report["warnings"]:
        print("WARNING %s" % warning)
    print("Result: %s" % ("OK" if report["ok"] else "FIX ERRORS BEFORE TRAINING"))
    return 0 if report["ok"] else 1


def command_train(args):
    adapter = _adapter(args.root)
    report = adapter.validate()
    if not report["ok"]:
        for error in report["errors"]:
            print("ERROR %s" % error)
        raise SystemExit("validation failed")
    print("Extracting features...")
    data = adapter.extract()
    print("  %d windows x %d features from %d runs (%d windows skipped for missing values)"
          % (data["X"].shape[0], len(data["names"]), len(set(data["groups"])), data["skipped_windows"]))
    bundle, result = partner_models.train_all(data)
    os.makedirs(os.path.dirname(os.path.abspath(args.model)), exist_ok=True)
    joblib.dump(bundle, args.model, compress=3)
    with open(os.path.splitext(args.model)[0] + "_report.json", "w") as handle:
        json.dump(result, handle, indent=2, default=str)
    _print_report(result)
    print("\nSaved %s" % args.model)


def _print_report(result):
    print("\nANOMALY DETECTION")
    for r in result["anomaly"]:
        if "skipped" in r:
            print("  %s: skipped (%s)" % (r["setup"], r["skipped"]))
            continue
        print("  setup %s: trained on %d windows; tested on %s" % (r["setup"], r["train_windows"], r["evidence"]))
        if "false_alarm_rate" in r:
            print("    false alarm rate on unseen normal data: %.1f%%" % (100 * r["false_alarm_rate"]))
        for label, v in r["labels"].items():
            print("    %-24s detected %5.1f%%  ROC AUC %.3f  top: %s" % (
                label, 100 * v["detection_rate"], v["roc_auc"],
                ", ".join("%s z=%.1f" % f for f in v["top_features"][:3])))
        for run, fraction in sorted(r.get("anomalous_fraction_per_run", {}).items()):
            print("    %-10s %5.1f%% of windows anomalous" % (run, 100 * fraction))
    c = result.get("classification")
    if c:
        print("\nFAULT CLASSIFICATION")
        if "skipped" in c:
            print("  skipped: %s" % c["skipped"])
        else:
            print("  test runs %s: accuracy %.3f, macro F1 %.3f" % (", ".join(c["test_runs"]), c["accuracy"], c["macro_f1"]))
            print("  top features: %s" % ", ".join("%s %.3f" % f for f in c["top_features"][:5]))
    rul = result.get("rul")
    if rul:
        print("\nREMAINING USEFUL LIFE")
        if "skipped" in rul:
            print("  skipped: %s" % rul["skipped"])
        else:
            s = rul["summary"]
            print("  leave one run out: MAE %.3f  RMSE %.3f  R2 %.2f (RUL fraction of life)" % (s["mae"], s["rmse"], s["r2"]))


def command_score(args):
    bundle = joblib.load(args.model)
    data = _adapter(args.root).extract()
    for entry in partner_models.score(bundle, data):
        line = "%-32s %5.1f%% windows anomalous  worst %.2fx threshold (%s)" % (
            entry["stream"], 100 * entry["anomalous_fraction"], entry["worst_ratio"],
            ", ".join("%s z=%+.1f" % f for f in entry["worst_features"][:2]))
        if "predicted_label" in entry:
            line += "  label %s (%.0f%% of windows)" % (entry["predicted_label"], 100 * entry["label_vote"])
        if "rul_fraction_last" in entry:
            line += "  RUL %.0f%% of life" % (100 * entry["rul_fraction_last"])
        print(line)


def _adapter(root):
    try:
        return PartnerDatasetAdapter(root)
    except SchemaError as exc:
        raise SystemExit("dataset description problem: %s" % exc)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command")
    template = sub.add_parser("template")
    template.add_argument("--out", default=os.path.join(config.EXTERNAL_DATA_DIR, "partner_example"))
    template.add_argument("--mode", default="fault_labels", choices=("fault_labels", "unlabeled", "run_to_failure"))
    for name in ("validate", "train", "score"):
        p = sub.add_parser(name)
        p.add_argument("--root", default=config.PARTNER_DATA_DIR)
        if name != "validate":
            p.add_argument("--model", default=os.path.join(config.MODEL_DIR, "partner_models.joblib"))
    args = parser.parse_args(argv)
    handler = {"template": command_template, "validate": command_validate,
               "train": command_train, "score": command_score}.get(args.command)
    if handler is None:
        parser.print_help()
        return 0
    return handler(args)


if __name__ == "__main__":
    sys.exit(main() or 0)
